### ISSUE TITLE
problems when running snATACutils_peaks_calling.sh

### ISSUE THREAD

**Issue by JiehuiHe** [Xieeeee/Droplet-Paired-Tag#1]
Hi,
Thank you for this wonderful repository and the scripts that replicate the outcomes. 

I have been utilizing the script 02.analysis/scripts/snATACutils_peaks_calling.sh for peak calling, but I can't find snATACutils_spm_corrected.R on line 42. I'm wondering where I can find it? 

Thanks,
Jiehui

**Comment by Xieeeee** [comment]
Hi Jiehui,
Thanks for your interest in trying Droplet Paired-Tag! I have uploaded the script you need. Also this spm correction script is directly adopted from https://github.com/yal054/snATACutils/tree/master/bin.

Best,
Yang

**Comment by JiehuiHe** [comment]
> Hi Jiehui, Thanks for your interest in trying Droplet Paired-Tag! I have uploaded the script you need. Also this spm correction script is directly adopted from https://github.com/yal054/snATACutils/tree/master/bin.
> 
> Best, Yang

I found it, thanks for your help！
