### ISSUE TITLE
PairArc rmat/dmat inputs and filtering to generate dual_frip_valid_cells.txt 

### ISSUE THREAD

**Issue by AndrewHardigan** [Xieeeee/Droplet-Paired-Tag#3]
Hello Yang ! thanks for a great resource paper and sharing your code.Posted this in prior comment which was closed so wasn't sure it would be seen or alert you to it , so making new issue.

I am trying to figure out exactly what steps you took to pair and filter the paired barcodes. I understand the general framework (run cell ranger count to generate raw bc matrix, and cell ranger atac to generate possorted_bam.bam which is then cleaned up, peaks called and clean fragment and FRIP fragment files generated).

I have been able to follow along using the DPT.help.R functions to run ImportArcFRiP, PlotArcFRiP, and PlotArcFragment. This generated a Sample_PFcells.txt file .

My question is in the PairArc function. What are you using as input ? i.e. what is rmat and dmat?

rmat I assume is just the cellranger count raw_feature_bc_matrix.h5. However, are you using raw_peak_bc_matrix.h5 from cellranger atac as the dmat? this would allow you to run the colsums part of the PairArc function as written. However, these peaks are not the ones we have called with macs2 in "08.proc_10Xarc_DNA.sh" and would instead be called by cellranger atac.

Or are you just taking the total counts for each cell barcode from PF_cells.txt file and using that somehow?

Finally, are you doing two separate cutoff steps (i.e. FRIP and fragment # cutoff as seen in the first panel for each mark of Sup Fig3A, generated from PlotArcFRIP) AND a total RNA read / total fragment count cutoff (generated from PlotArcPair)?

Apologize for my confusion. just trying to find file inputs and expected output to generate the dual_frip_valid_cells.txt .

Thank you again for your help and this resource

**Comment by Xieeeee** [comment]
Hi AndrewHardigan,
Thanks for your interest. For your question:
1. `PairArc` input is RNA raw matrix and DNA genomic bin matrix (or peak matrix). We used bin matrix for clustering for a better clustering performance, and you can use either `sinto` or `snapatac2` to generate that.
2. Yes, I am doing a two-steps filtering to filter DNA based on frag + frip first, then paired with rna for the second round of filtering. Thanks for pointing this out; I just realized I missed to upload the code. Now you can find it here: [Valid cells overlapped with FRiP](https://github.com/Xieeeee/Droplet-Paired-Tag/blob/main/01.pre-process/notebook/01.Pre-process.ipynb)

Best,
Yang
